name: Deploy to Firebase Hosting

on:
   push:
      branches:
         - main # Set the branch you want to deploy from

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Set up Node.js
           uses: actions/setup-node@v3
           with:
              node-version: "14" # Set the Node.js version you are using

         - name: Install dependencies
           run: npm install

         - name: Build the project
           run: npm run build # Adjust according to your build script

         - name: Deploy to Firebase
           uses: wzieba/Firebase-Action@v2
           with:
              args: deploy --only hosting
           env:
              FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
              # For service account key, you need to use the following:
              # FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
